Metadata:
  Version: 1.0  # Please att version if the standard changes
  Created: 2022.02.21  # When the file was created
LinearizedModels:
  - EqPoint: [0,1] # Equilibrium point (q1,q2)
    Gains:
      - {Kp: 1,Ki: 1,Kd: 1} # Gains for first controller
      - {Kp: 1,Ki: 1,Kd: 1} # Gains for first controller
  - EqPoint: [0,1] # Equilibrium point (q1,q2)
    Gains:
      - {Kp: 1,Ki: 1,Kd: 1} # Gains for first controller
      - {Kp: 1,Ki: 1,Kd: 1} # Gains for first controller